language: python
python: 3.5
services:
    - mysql
before_install:
    - mysql -u root -e 'create database nao;'
install:
    - pip install flask
    - pip install flask_sqlalchemy
    - pip install https://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.1.3.tar.gz
env:
    - FLASK_ENV=TEST
script: python -m unittest discover
