
# GENERIC CONTENT
STATUS_KEY = "result"
STATUS_SUCCESS = "SUCCESS"
STATUS_FAILURE = "FAILURE"

# COMMAND CONTENT
COMMAND_KEY = "command"
ADD_COMMAND_EXT = "/add_command"
GET_LAST_COMMAND_EXT = "/get_last_command"

# ACCOUNT CONTENT
REGISTER_EXT = "/register"
LOGIN_EXT = "/login"
COOKIE_KEY = "session-id"
USERNAME_KEY = "username"
PASSWORD_KEY = "password"
